export const PlayerActions = {
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',
  NEXT_SCREEN: 'NEXT_SCREEN',
  RESET: 'RESET',
  SET_VISIBLE_START: 'SET_VISIBLE_START',
  SET_VISIBLE_END: 'SET_VISIBLE_END',
};
